package etour.pojo;
// Generated 21 Jan, 2020 1:04:08 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

//import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Bookingdetail generated by hbm2java
 */
@Entity
@Table(name = "bookingdetail", catalog = "etour")
public class Bookingdetail implements java.io.Serializable {

	private Integer bookingid;
	private Datepackagedetail datepackagedetail;
	private Passengerdetail passengerdetail;
	private Customerdetail customerdetail;
	private Packagecompletedetail packagecompletedetail;
	private Date bookingdate;
	private String activestatus;
	//private Set<Passengerdetail> passengerdetails = new HashSet<Passengerdetail>(0);

	public Bookingdetail() {
	}

	public Bookingdetail(Datepackagedetail datepackagedetail, Passengerdetail passengerdetail,
			Customerdetail customerdetail, Packagecompletedetail packagecompletedetail, Date bookingdate,
			String activestatus) {
		this.datepackagedetail = datepackagedetail;
		this.passengerdetail = passengerdetail;
		this.customerdetail = customerdetail;
		this.packagecompletedetail = packagecompletedetail;
		this.bookingdate = bookingdate;
		this.activestatus = activestatus;
		//this.passengerdetails = passengerdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bookingid", unique = true, nullable = false)
	public Integer getBookingid() {
		return this.bookingid;
	}

	public void setBookingid(Integer bookingid) {
		this.bookingid = bookingid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "datepackageid")
	public Datepackagedetail getDatepackagedetail() {
		return this.datepackagedetail;
	}

	public void setDatepackagedetail(Datepackagedetail datepackagedetail) {
		this.datepackagedetail = datepackagedetail;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "passengerid")
	public Passengerdetail getPassengerdetail() {
		return this.passengerdetail;
	}

	public void setPassengerdetail(Passengerdetail passengerdetail) {
		this.passengerdetail = passengerdetail;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customerid")
	public Customerdetail getCustomerdetail() {
		return this.customerdetail;
	}

	public void setCustomerdetail(Customerdetail customerdetail) {
		this.customerdetail = customerdetail;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "packageid")
	public Packagecompletedetail getPackagecompletedetail() {
		return this.packagecompletedetail;
	}

	public void setPackagecompletedetail(Packagecompletedetail packagecompletedetail) {
		this.packagecompletedetail = packagecompletedetail;
	}

	//@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "bookingdate", length = 10)
	public Date getBookingdate() {
		return this.bookingdate;
	}

	public void setBookingdate(Date bookingdate) {
		this.bookingdate = bookingdate;
	}

	@Column(name = "activestatus", length = 10)
	public String getActivestatus() {
		return this.activestatus;
	}

	public void setActivestatus(String activestatus) {
		this.activestatus = activestatus;
	}

	/*@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "bookingdetail")
	public Set<Passengerdetail> getPassengerdetails() {
		return this.passengerdetails;
	}

	public void setPassengerdetails(Set<Passengerdetail> passengerdetails) {
		this.passengerdetails = passengerdetails;
	}*/

}
