package etour.pojo;
// Generated 21 Jan, 2020 1:04:08 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorysubcategory generated by hbm2java
 */
@Entity
@Table(name = "categorysubcategory", catalog = "etour")
public class Categorysubcategory implements java.io.Serializable {

	private Integer catsubid;
	private Integer categoryid;
	private String categoryname;
	private String categoryimage;
	private Integer subcategoryid;
	private String subcategoryname;
	private String subcategoryimage;
	private String eofflag;
	private Set<Packagecompletedetail> packagecompletedetails = new HashSet<Packagecompletedetail>(0);

	public Categorysubcategory() {
	}

	public Categorysubcategory(Integer categoryid, String categoryname, String categoryimage, Integer subcategoryid,
			String subcategoryname, String subcategoryimage, String eofflag,
			Set<Packagecompletedetail> packagecompletedetails) {
		this.categoryid = categoryid;
		this.categoryname = categoryname;
		this.categoryimage = categoryimage;
		this.subcategoryid = subcategoryid;
		this.subcategoryname = subcategoryname;
		this.subcategoryimage = subcategoryimage;
		this.eofflag = eofflag;
		this.packagecompletedetails = packagecompletedetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "catsubid", unique = true, nullable = false)
	public Integer getCatsubid() {
		return this.catsubid;
	}

	public void setCatsubid(Integer catsubid) {
		this.catsubid = catsubid;
	}

	@Column(name = "categoryid")
	public Integer getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	@Column(name = "categoryname", length = 50)
	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	@Column(name = "categoryimage", length = 50)
	public String getCategoryimage() {
		return this.categoryimage;
	}

	public void setCategoryimage(String categoryimage) {
		this.categoryimage = categoryimage;
	}

	@Column(name = "subcategoryid")
	public Integer getSubcategoryid() {
		return this.subcategoryid;
	}

	public void setSubcategoryid(Integer subcategoryid) {
		this.subcategoryid = subcategoryid;
	}

	@Column(name = "subcategoryname", length = 50)
	public String getSubcategoryname() {
		return this.subcategoryname;
	}

	public void setSubcategoryname(String subcategoryname) {
		this.subcategoryname = subcategoryname;
	}

	@Column(name = "subcategoryimage", length = 50)
	public String getSubcategoryimage() {
		return this.subcategoryimage;
	}

	public void setSubcategoryimage(String subcategoryimage) {
		this.subcategoryimage = subcategoryimage;
	}

	@Column(name = "eofflag", length = 5)
	public String getEofflag() {
		return this.eofflag;
	}

	public void setEofflag(String eofflag) {
		this.eofflag = eofflag;
	}

	/*@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "categorysubcategory")
	public Set<Packagecompletedetail> getPackagecompletedetails() {
		return this.packagecompletedetails;
	}

	public void setPackagecompletedetails(Set<Packagecompletedetail> packagecompletedetails) {
		this.packagecompletedetails = packagecompletedetails;
	}*/

}
